name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Esto corre todos los días a medianoche
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate README
        run: |
          echo "## My Statistics" > README.md
          echo "" >> README.md
          echo '<p align="left">' >> README.md
          echo '  <a href="https://github.com/sebas290">' >> README.md
          echo '    <img width="49.5%" src="https://github-readme-stats.vercel.app/api?username=tu-usuario&show_icons=true&theme=gruvbox&hide_border=true" />' >> README.md
          echo '    <img width="49.5%" src="https://github-readme-streak-stats.herokuapp.com/?user=tu-usuario&theme=gruvbox&hide_border=true" />' >> README.md
          echo '  </a>' >> README.md
          echo '</p>' >> README.md

      - name: Commit changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add README.md
          git commit -m "📊 Update README stats"
          git push
